


# try랑 except를 연습시키는 건 맞는 것 같은데, 왜 except 문이 제대로 작동하지 않는지에 대해서는 좀 더 고민이 필요한 문제
# def multiply(*args):
#     c = 1
#     try:
#         for x in args:
#             c = c*x
#         print(c)
#
#     except NameError:
#         print("에러발생")
#
# multiply(1, 2, 삼, 4)
#

